Improve gcloud CLI experience
extenda/actions pull request #266
Opened 2020-11-06 14:13 UTC by michaelwittig

with the CLOUDSDK_CORE_PROJECT env variable the gcloud CLI will just work after setup.

I was not able to build the dist/index.js file. No matter if I use `npm run build` or `npm run build:docker`, I get very different outputs for a lot of files

2020-11-06 14:17 UTC, sasjo requested changes
Changes looks good to me!

To make the build pass, run `npm run build` and commit the changed dist file(s). You may need to run `npm ci` first.

To make the commitlint pass, add `feat: ` to the PR title after you've pushed your second commit. If you install pre commit on the repo, it will validate each commit message.

2020-11-06 15:14 UTC, michaelwittig commented on .scripts/modules.js
> +  npmArgument: JSON.parse(process.env.npm_config_argv || '{"original": []}').original.join(' '),
@sasjo let me know if I should remove it from this PR. It's a bug but not related to my original goal here...

2020-11-07 09:44 UTC, sasjo approved these changes

2020-11-07 09:51 UTC, merged

2020-11-23 12:41 UTC, michaelwittig commented
thanks @sasjo for fixing the dist files