fix: Add countryCode to DB details
extenda/actions pull request #333
Opened 2021-03-26 11:13 UTC by mar-schmidt

2021-03-26 11:25 UTC, sasjo requested changes
country code is an optional input so the action can only concatenate tenantName and countryCode if the code is set.

2021-03-26 15:07 UTC, mar-schmidt commented
> country code is an optional input so the action can only concatenate tenantName and countryCode if the code is set.

Fixed.

2021-03-26 19:45 UTC, sasjo requested changes
Can you add a test to verify output if country code is absent. Pretty sure that missing input becomes empty string so we need to make sure we handle that.

2021-03-26 19:45 UTC, sasjo commented on txengine-deploy/src/env-config.js
> +const getConditionalCountryCodeString = (countryCode) => (typeof (countryCode) !== 'undefined' ? `${countryCode}_` : '');
I think this will fail if countryCode is a blank string.

2021-03-27 12:03 UTC, mar-schmidt commented
> Can you add a test to verify output if country code is absent. Pretty sure that missing input becomes empty string so we need to make sure we handle that.

Is this test not sufficient for absent country code?
```
test('It can handle optional country code')
```

2021-03-29 06:52 UTC, sasjo approved these changes

2021-03-29 06:52 UTC, merged