feat: Add action for fetching identity token
extenda/actions pull request #356
Opened 2021-05-27 12:42 UTC by akovtun-extenda

2021-05-27 13:08 UTC, Santos92 commented on identity-token/action.yml
> +    description: Comma-separated list of audiences which are the intended recipients of the token.
Don't think our helper library supports multiple audiences :/

2021-05-27 13:10 UTC, sasjo requested changes
The output variable should be fixed. Is the safe-guards to only allow this in staging enforced inside GCP using IAM permissions or should the action also check something on the SA?

2021-05-27 13:10 UTC, sasjo commented on identity-token/action.yml
> +runs:
The action should also specify an `outputs` section containing the `identity-token` according to the README.

2021-05-27 13:10 UTC, sasjo commented on identity-token/src/index.js
> +  core.setOutput('iam-token', token);
The output should be `identity-token` according to the README.

2021-05-27 13:15 UTC, akovtun-extenda commented
None of the ci-cd-pipeline SAs have a token creator role which is required to be able to generate tokens. This role will be granted only in staging.

2021-05-27 14:40 UTC, Santos92 approved these changes

2021-05-27 15:27 UTC, akovtun-extenda commented
do not merge, please. Need to update the project's module first, to add a needed role for the ci-cd SA.

2021-05-28 08:32 UTC, sasjo approved these changes
LGTM

2021-05-31 07:18 UTC, merged